games:
  yume:
    name: "Yume Nikki"
    namespace: "3000"
  2kki:
    name: "Yume 2kki"
    namespace: "3002"
  flow:
    name: "Dotflow"
    namespace: "3004"
  someday:
    name: "Someday"
    namespace: "3006"
  deepdreams:
    name: "Deep Dreams"
    namespace: "3008"
  prayers:
    name: "Answered Prayers"
    namespace: "3010"
  amillusion:
    name: "Amillusion"
    namespace: "3012"
  unevendream:
    name: "Uneven Dream"
    namespace: "3014"
    protagonists:
      kubotsuki: "Category:Kubotsuki's Worlds"
      totsutsuki: "Category:Totsutsuki's Worlds"
  braingirl:
    name: "Braingirl"
    namespace: "3016"
  unconscious:
    name: "Collective Unconscious"
    namespace: "3018"
  cerasus:
    name: "Cerasus"
    namespace: "3020"
  muma:
    name: "Muma Rope"
    namespace: "3022"
  genie:
    name: "Dream Genie"
    namespace: "3026"
  mikan:
    name: "Mikan Muzou"
    namespace: "3028"
  ultraviolet:
    name: "Ultra Violet"
    namespace: "3030"
  sheawaits:
    name: "She Awaits"
    namespace: "3032"
  oversomnia:
    name: "Oversomnia"
    namespace: "3034"
  tagai:
    name: "Yume Tagai"
    namespace: "3036"
    protagonists:
      makitsuki: "Category:Makitsuki's Worlds"
      sakiyuki: "Category:Sakiyuki's Worlds"
  tsushin:
    name: "Yume Tsushin"
    namespace: "3038"
  nostalgic:
    name: "NostAlgic"
    namespace: "3040"
  if:
    name: "If"
    namespace: "3042"
  unaccomplished:
    name: "Unaccomplished"
    namespace: "3044"